# Generated by Django 5.1.1 on 2024-12-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_customuser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
