FROM rabbitmq:3-management

EXPOSE 5672 15672

# Рекомендуется: Настройка пользователя и пароля через переменные окружения
# ENV RABBITMQ_DEFAULT_USER admin
# ENV RABBITMQ_DEFAULT_PASS strongpassword

CMD ["rabbitmq-server"]